### ISSUE TITLE
Why use user.dir?

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#12]
https://github.com/nitishgupta/wikiparser/blob/f5c4207c37ff27023d754c05dbdeb9f89f5c47c6/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/PageMapLineParser.java#L39

I don't understand why are you using project path? The dir path to the output will given by the user as an argument or should be a path hardcoded in Constants.

**Comment by rxtan2** [comment]
Just to clarify, the user should provide the dir path and all of the outputs from parsing the 3 files will be placed into  one single folder?

**Comment by nitishgupta** [comment]
The user will provide the out directory path. The output fileneames should
already be hardcoded in the constants

**Comment by rxtan2** [comment]
Resolved - Output file is now provided by the user as an argument to the shell script runjwplparser.sh
