### ISSUE TITLE
Use Paths to join path 

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#13]
https://github.com/nitishgupta/wikiparser/blob/f5c4207c37ff27023d754c05dbdeb9f89f5c47c6/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/PageMapLineParser.java#L47

To join dirs / file paths use Paths class

See example here : https://stackoverflow.com/questions/34459486/joining-paths-in-java

**Comment by rxtan2** [comment]
Resolved - Used Paths class to join directory and file paths in the following classes:

1) PageMapLineParser
2) CategoryPagesParser
3) CategoryParser
