### ISSUE TITLE
Need for check?

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#14]
https://github.com/nitishgupta/wikiparser/blob/f5c4207c37ff27023d754c05dbdeb9f89f5c47c6/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/PageMapLineParser.java#L90

Why is there a check here? If it is to avoid newline at the end of the file it is not intended. We would like new line at the end of a file. Take care of this globally in project. Also, write comments in the code.

**Comment by rxtan2** [comment]
Resolved - This check was originally intended to avoid a newline at the end of the file,  This check is removed in the following classes:

1) PageMapLineParser
2) CategoryPagesParser
3) CategoryParser
