### ISSUE TITLE
Single Function?

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#15]
https://github.com/nitishgupta/wikiparser/blob/f5c4207c37ff27023d754c05dbdeb9f89f5c47c6/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/PageMapLineParser.java#L38

This shouldn't be a single function. It is very natural to break this into different functions.

**Comment by rxtan2** [comment]
Resolved - Break writeToFiles function into different relevant functions for each output in the following classes:

1) PageMapLineParser
2) CategoryPagesParser
3) CategoryParser
