### ISSUE TITLE
Comment inside function definition

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#16]
https://github.com/nitishgupta/wikiparser/blob/55453f8f7b3d3c9c81c51c9a48f30e155309b0ca/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/PageMapLineParser.java#L14

I think I mentioned this before. Can you move all function comments, just inside the definition. 
Eg. 
`private void writePageIds(){`
`    // Write list of all page ids`
`  Path filepath .......`
`}`

**Comment by rxtan2** [comment]
Resolved - Moved all function comments inside the definitions in the following classes:

1) PageMapLineParser: Lines 47, 65, 83, 101, 119
2) CategoryPagesParser: Lines 31, 53, 69
