### ISSUE TITLE
Why need this object?

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#18]
https://github.com/nitishgupta/wikiparser/blob/abad80d329e5094dec2d851caea5c736d4e9f269/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/DataMachine.java#L42

Why do we need this object here? Looks like it is for logging. But that should be independent of the WikiExtractParser class.

**Comment by rxtan2** [comment]
Resolved: Removed this object
