### ISSUE TITLE
Update the List check

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#21]
https://github.com/nitishgupta/wikiparser/blob/32de64197a09f7be8a981edf18c12f14b4958590/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/jwplparsers/PageMapLineParser.java#L208

Change this line to 
`if ((pageTitle.startsWith("List_of") || pageTitle.startsWith("Lists_of")) && (id == resolvedId)) {`

**Comment by rxtan2** [comment]
Resolved: https://github.com/nitishgupta/wikiparser/blob/57ba9bcc98936fb0c2f71f398e403873d7408ad6/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/jwplparsers/PageMapLineParser.java#L208
