### ISSUE TITLE
Change the check

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#22]
https://github.com/nitishgupta/wikiparser/blob/a656686691a8eca33e7eedab04d80b666087d105/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/jwplparsers/PageMapLineParser.java#L208

```
if (id.equals(resolvedId)) {
    if (pageTitle.startsWith("List_of") || pageTitle.startsWith("Lists_of")) {
        # do something
   }
}
```

**Comment by rxtan2** [comment]
Resolved: https://github.com/nitishgupta/wikiparser/blob/1b35f7f2f05ad0c9968437dc06126744693472cd/src/main/java/edu/illinois/cs/cogcomp/wikiparser/jwpl/jwplparsers/PageMapLineParser.java#L208
