### ISSUE TITLE
language not always detected

### ISSUE THREAD

**Issue by solene-evain** [nitishgupta/wikiparser#29]
Hi! 
I'm using your tool to create a dictionary for automatic speech recognition. Using the 'french' argument was supposed to catch the french section of words only but this doesn't always work. For e.g., I have the word "wollte" (german) that do not seem to have a 'french' section when searching it on wiktionary. Yet, when I fetch the word with ('wollte','french'), it catches something. 
I don't know if you're still granting support for the wikiparser but I thought it was quite an important problem to raise.

**Comment by nitishgupta** [comment]
Sorry, this repo is not under active development.
