### ISSUE TITLE
Missing \n

### ISSUE THREAD

**Issue by nitishgupta** [nitishgupta/wikiparser#5]
https://github.com/nitishgupta/wikiparser/blob/master/edu/illinois/cs/cogcomp/wikiparser/wikiparse/FileParser.java#L90

There should be a .append("\n") otherwise between lines there will be no break.

**Comment by rxtan2** [comment]
I did that in Line 92.

**Comment by nitishgupta** [comment]
Should be inside the check. Otherwise if a line is empty, there will be two carriage returns.
